---
- name: Configure web server
  hosts: all
  become: true
  tasks:
    - name: Install Apache web server
      apt:
        name: apache2
        state: present

    - name: Start Apache web server
      service:
        name: apache2
        state: started

    - name: Launch google.com in browser
      uri:
        url: https://www.google.com/
        method: get

